# pages-collection
# a Jekyll Digital Collection Generator 
# designed for GH-Pages

# Site settings

# title of site appears in banner
title: GH-Pages Collection
# tagline appears in banner
tagline: a theme for building simple digital exhibits
# description appears in meta tags and other locations
description: "A more complete description that will appear in meta tags and other locations where appropriate"
# keywords appear in meta tags 
keywords: "university of idaho, digital collections, digital humanities"
# creator email for meta tags
email: ewilliamson@uidaho.edu

# url is your gh-pages base, username.github.io
url: https://uidaholib.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /pages-collection

# google services
# leave these blank or comment out to NOT include google code
google-tracking-id: "UA-74844011-1"
google-cse-id: "002151703305773322890:1pu3smhw1t8"

# build settings
permalink: pretty

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build